/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Lombok library to improve your Java. See https://projectlombok.org/features/
    //id("io.freefair.lombok") version "8.4"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use TestNG framework, also requires calling test.useTestNG() below
    testImplementation(libs.testng)
    // HTTP-client. https://github.com/rest-assured/rest-assured/wiki/GettingStarted
    testImplementation ("io.rest-assured:rest-assured:5.4.0")
    testImplementation ("io.rest-assured:json-path:5.4.0")
    // Asserts. https://assertj.github.io/doc/#assertj-overview
    testImplementation("org.assertj:assertj-core:3.25.1")


//    implementation(libs.guava)
    implementation("org.projectlombok:lombok:1.18.30")
    implementation("org.slf4j:slf4j-api:2.0.11")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.1")
    implementation("net.datafaker:datafaker:2.0.2")
    implementation("com.github.java-json-tools:json-patch:1.13")

    compileOnly ("org.projectlombok:lombok:1.18.30")
    annotationProcessor ("org.projectlombok:lombok:1.18.30")

    testCompileOnly ("org.projectlombok:lombok:1.18.30")
    testAnnotationProcessor ("org.projectlombok:lombok:1.18.30")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.mtp.aqa.wrkshp.api.arch.App")
}

tasks.named<Test>("test") {
    // Use TestNG for unit tests.
    useTestNG()
}
